/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i calls_adaptor.h -a :calls_adaptor.cpp ../../Yottagram/Yottagram/com.verdanditeam.yottagram.calls.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "calls_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CallsAdaptor
 */

CallsAdaptor::CallsAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CallsAdaptor::~CallsAdaptor()
{
    // destructor
}

void CallsAdaptor::callReady()
{
    // handle method call com.verdanditeam.yottagram.calls.callReady
    QMetaObject::invokeMethod(parent(), "callReady");
}

void CallsAdaptor::discardCall()
{
    // handle method call com.verdanditeam.yottagram.calls.discardCall
    QMetaObject::invokeMethod(parent(), "discardCall");
}

void CallsAdaptor::newCall(const QString &callerName, bool incoming)
{
    // handle method call com.verdanditeam.yottagram.calls.newCall
    QMetaObject::invokeMethod(parent(), "newCall", Q_ARG(QString, callerName), Q_ARG(bool, incoming));
}

