/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a calls_adaptor.h: ../../Yottagram/Yottagram/com.verdanditeam.yottagram.calls.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CALLS_ADAPTOR_H
#define CALLS_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.verdanditeam.yottagram.calls
 */
class CallsAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.verdanditeam.yottagram.calls")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.verdanditeam.yottagram.calls\">\n"
"    <method name=\"newCall\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"callerName\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"incoming\"/>\n"
"    </method>\n"
"    <method name=\"discardCall\"/>\n"
"    <method name=\"callReady\"/>\n"
"    <signal name=\"discard\"/>\n"
"    <signal name=\"accept\"/>\n"
"    <signal name=\"muteMicrophone\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"mute\"/>\n"
"    </signal>\n"
"    <signal name=\"changeSpeakerMode\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"loudspeaker\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    CallsAdaptor(QObject *parent);
    virtual ~CallsAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void callReady();
    void discardCall();
    void newCall(const QString &callerName, bool incoming);
Q_SIGNALS: // SIGNALS
    void accept();
    void changeSpeakerMode(bool loudspeaker);
    void discard();
    void muteMicrophone(bool mute);
};

#endif
